#!/usr/bin/env node
const yargs = require('yargs');
const { readConfig } = require('./helpers/config');
const { config } = require('./builders/config');
const { exec } = require('./builders/exec');
// const { readme } = require('./commands/readme');
const algorithms = require('./builders/algorithm');
const pipelines = require('./builders/pipeline');
const dryRun = require('./builders/dry-run');
const sync = require('./builders/sync');
const main = async () => {
  const configFile = await readConfig();

  yargs.config(configFile);
  yargs.command(exec)
  yargs.command(algorithms)
  yargs.command(pipelines)
  yargs.command(dryRun)
  yargs.command(sync)
  yargs.command(config)
  yargs.options('rejectUnauthorized', {
    description: 'set to false to ignore certificate signing errors. Useful for self signed TLS certificate',
    type: "boolean",
    default: "true"
  })
  yargs.options('endpoint', {
    description: 'url of hkube api endpoint',
    type: "string",
    default: 'http://127.0.0.1'
  })
    .demandCommand()
    .help()
    .epilog('for more information visit http://hkube.io')
    .completion()
    .argv;
}

main();
